// Textdatei fr Outlook Express 5
OutputFile    "c:\temp\par.txt"
Delimiter     ";"
FieldUpdate   "Titel"       trim(PAR->Allo)
FieldUpdate   "Vorname"     trim(PAR->Vorname)
FieldUpdate   "Nachname"     trim(PAR->Firme)
FieldUpdate   "Name"        trim1(PAR->Allo)+trim1(PAR->Vorname)+trim(PAR->Firme)
FieldUpdate   "Straáe (privat)"     trim(ParStreet())
FieldUpdate   "E-Mail-Adresse"    '"'+trim(PAR->email)+'"'
FieldUpdate   "Land (privat)"       trim(NatField(PAR->Pays,"NAT->Name"))
FieldUpdate   "Postleitzahl (privat)"         trim(PAR->CP)
FieldUpdate   "Ort (privat)"        trim(PlzName(PAR->Pays,PAR->CP))
FieldUpdate   "Telefon (privat)"         trim(PAR->Tel)
FieldUpdate   "Fax (privat)"        trim(PAR->Fax)

// Siehe auch DOS2WIN.CVT
convert "„" to "ä"
convert "" to "Ä"
convert "”" to "ö"
convert "™" to "Ö"
convert "" to "ü"
convert "š" to "Ü"
convert "á" to "ß"
convert "…" to "à"
convert "ƒ" to "â"
convert "‚" to "é"
convert "ˆ" to "ê"
convert "Š" to "è"
convert "Œ" to "î"
convert "“" to "ô"
convert "–" to "û"
convert "—" to "ù"
convert "‰" to "ë"
convert "‡" to "ç"
convert "ñ" to "±"
