[=p_SetWidth(76)]
[set montant S10]
[=SetDateFormat(tr("mmmm d, yyyy","d. mmmm yyyy","d mmmm yyyy"))]
[=SetTplHeader({||fparse("VENHDR.TPL")})]
[=SetTplFooter({||fparse("VENFTR.TPL")},.t.)]
[=mparse("VENINTRO.TPL")]
[ven memo]
[tab define " Ä "]
[=!'T'$VEN->Attrib.or.p_addColumn(3,"TR","Pos","[=VnlNum()]")]
[=p_addColumn(0,"TL",\
  tr("Description","Beschreibung","Description"),\
  if("Q"$VEN->Attrib,"[vnl descript amt]","[vnl descript amtq]"))]
[=!'Q'$VEN->Attrib.or.p_addColumn(LenQte(),"TL",tr("Qty","Menge","Qt‚"),"[vnl qt t]")]
[=!'U'$VEN->Attrib.or.p_addColumn(LenMntF(),"BR",tr("Unit pr.","S-Preis","prix u."),"[vnl pu t]")]
[=!'N'$VEN->Attrib.or.p_addColumn(LenMntF(),"BR",tr("Price","Preis","Prix"),"[vnl htva t]")]
[=!'C'$VEN->Attrib.or.p_addColumn(LenMntF(),"BR",tr("incl.VAT","inkl.MWSt","tvac"),"[vnl tvac t]")]
[tab begin]
[ven vnllist "[tab exec]"]
[tab end]
[=mparse("VENTOTAL.TPL")]
[set align l]
[=fparse("VENBOTTM.TPL","TMP.TXT",NIL,NIL,.t.)]
[etc goto -mlcount(memoread("TMP.TXT"))]
[=fparse("VENBOTTM.TPL")]
